# Generated by Django 4.2 on 2024-03-02 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_app.basemodel')),
                ('title', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('about', models.TextField(blank=True)),
            ],
            bases=('portfolio_app.basemodel',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_app.basemodel')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, verbose_name='UCCS Email')),
                ('major', models.CharField(blank=True, choices=[('CSCI-BS', 'BS in Computer Science'), ('CPEN-BS', 'BS in Computer Engineering'), ('BIGD-BI', 'BI in Game Design and Development'), ('BICS-BI', 'BI in Computer Science'), ('BISC-BI', 'BI in Computer Security'), ('CSCI-BA', 'BA in Computer Science'), ('DASE-BS', 'BS in Data Analytics and Systems Engineering')], max_length=200)),
                ('studentPortfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.portfolio')),
            ],
            bases=('portfolio_app.basemodel',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_app.basemodel')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('studentPortfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.portfolio')),
            ],
            bases=('portfolio_app.basemodel',),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentProjects', to='portfolio_app.project'),
        ),
    ]
