# Generated by Django 4.2 on 2024-03-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='studentPortfolio',
        ),
    ]
