# Generated by Django 4.2 on 2024-03-19 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_portfolio_studentreference_project_studentreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='studentPortfolio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio_app.portfolio'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentPortfolio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio_app.portfolio'),
        ),
    ]
