# Generated by Django 4.2 on 2024-03-19 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_student_studentportfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentProjects', to='portfolio_app.project'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='studentReference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='studentPortfolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio_app.portfolio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='studentReference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.student'),
        ),
    ]
