# Generated by Django 4.2 on 2024-03-19 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_remove_portfolio_projects_portfolio_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='studentPortfolio',
        ),
        migrations.RemoveField(
            model_name='project',
            name='studentReference',
        ),
    ]
