# Generated by Django 4.2 on 2024-03-19 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_remove_project_studentportfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='studentReference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio_app.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentPortfolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio_app.portfolio'),
        ),
    ]
